---
- name: Create primary network interface
  local_action:
    module: ec2_eni
    region: "{{ stack.region }}"
    security_groups: "{{ security_group_ids }}"
    subnet_id: "{{ subnet_id }}"
    private_ip_address: "{{ private_ip_address }}"
    state: present
  register: net_if


